name: Build and push

on:
  push:
  pull_request:

jobs:
  base-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version:
          - "9.5"
          - "9.6"
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            "PGTARGET=16"
          target: "build-${{ matrix.pg_version }}"
          tags: "simpliandy/pgautoupgrade:build-${{ matrix.pg_version }}"
          cache-to: type=inline
          cache-from: type=registry,ref=simpliandy/pgautoupgrade:build-${{ matrix.pg_version }}

  target-images:
    runs-on: ubuntu-latest
    needs: base-images
    env:
      CACHE_FROM: |
        type=registry,ref=simpliandy/pgautoupgrade:build-9.5
        type=registry,ref=simpliandy/pgautoupgrade:build-9.6
        type=registry,ref=simpliandy/pgautoupgrade:build-10
        type=registry,ref=simpliandy/pgautoupgrade:build-11
        type=registry,ref=simpliandy/pgautoupgrade:build-12
        type=registry,ref=simpliandy/pgautoupgrade:build-13
        type=registry,ref=simpliandy/pgautoupgrade:build-14
        type=registry,ref=simpliandy/pgautoupgrade:build-15
        type=registry,ref=simpliandy/pgautoupgrade:${{ matrix.pg_target }}-alpine3.18

    strategy:
      matrix:
        pg_target:
          - "13"
          - "14"
          - "15"
          - "16"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: "simpliandy/pgautoupgrade:${{ matrix.pg_target }}-alpine3.18"
          build-args: |
            "PGTARGET=${{ matrix.pg_target }}"
          cache-to: type=inline
          cache-from: "${{ env.CACHE_FROM }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test image
        run: |
          make test
        env:
          PGTARGET: ${{ matrix.pg_target }}

      - name: Push image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          tags: "simpliandy/pgautoupgrade:${{ matrix.pg_target }}-alpine3.18"
          push: true
          cache-to: type=inline
          cache-from: "${{ env.CACHE_FROM }}"
